modLoader = "javafml"
loaderVersion = "[${loader_version},)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "viscript_npc"
version = "1.0.0"
displayName = "ViScriptNpc"
authors = "zhenshiz"
description = "Visual(ldlib 2) and Script(rhino) to edit npc"
logoFile = "icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.viscript_npc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.197,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscript_npc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "viscript_npc.mixins.json"

[features.viscript_npc]
openGLVersion="[3.2,)"
